version: '3.4'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
       - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ipcalf.conf:/etc/nginx/conf.d/ipcalf.conf
      - ./nginx/ipcalf/src:/usr/share/nginx/html/
